### ISSUE TITLE
Update PR template in GIT

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-tutorials#17]
#### Expected behavior 
Pull Request template should be clear. 

#### Actual behavior
We provide a link ( https://fluentweb.com/prototyping/contribution-policy#pull-requests ) which is an empty page.

#### Steps to reproduce the problem
Create a new Pull Request in fast-tutorials

#### Specifications (hardware, software, configurations)

*Attach any helpful screenshots or videos to expedite the process.*
![capture1](https://user-images.githubusercontent.com/37851214/38042321-eaaf8d76-3268-11e8-97a3-141d4fdfc5ca.PNG)

**Comment by chrisdholt** [comment]
With @awentzel changes to the docs site, the new link should likely be: https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md#pull-request-guidance
