### ISSUE TITLE
Don't override registry globally

### ISSUE THREAD

**Issue by RobertGoins** [Microsoft/fast-tutorials#6]
The instructions:
registry=registry=https://fluentweb.pkgs.visualstudio.com/_packaging/ms.fw/npm/registry/
always-auth=true

result in overriding your npm registry, which falls back to the public npm repository but if you have any other private repositories (like if you use vsts package management for your own project) this blocks you from using them.  This project should instead use scoping and override the registry for just that scope.  For example:

;.npmrc
@fluentweb:registry=https://fluentweb.pkgs.visualstudio.com/_packaging/ms.fw/npm/registry/
always-auth=true

That would override the registry for only that scoped package.
see:
https://docs.npmjs.com/files/npmrc

**Comment by janechu** [comment]
Closed by https://github.com/Microsoft/fast-tutorials/pull/7
